// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { defineConfig } from "prisma/config";
import dotenv from "dotenv"
import path from "path"

dotenv.config({
  path: path.resolve(import.meta.dirname, "../../.env")
})

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // `prisma generate` runs while Railway builds the image, before runtime
    // variables are injected. Database commands still receive DATABASE_URL.
    url: process.env.DATABASE_URL || "postgresql://build:build@localhost:5432/build",
  },
});
